
export SOURCE_CODE=$PWD
if ! docker info &>/dev/null; then
  if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
    export DOCKER_HOST='tcp://localhost:2375'
  fi
fi

function propagate_env_vars() {
  CURRENT_ENV=$(printenv)

  for VAR_NAME; do
    echo $CURRENT_ENV | grep "${VAR_NAME}=" > /dev/null && echo "--env $VAR_NAME "
  done
}

docker pull --quiet "$CODE_QUALITY_IMAGE"
docker run \
  $(propagate_env_vars \
    SOURCE_CODE \
    TIMEOUT_SECONDS \
    CODECLIMATE_DEBUG \
    CODECLIMATE_DEV \
    REPORT_STDOUT \
    REPORT_FORMAT \
    ENGINE_MEMORY_LIMIT_BYTES \
    CODECLIMATE_PREFIX \
  ) \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  "$CODE_QUALITY_IMAGE" /code